### ISSUE TITLE
Different dictionaries

### ISSUE THREAD

**Issue by gusbemacbe** [gamag/ka_GE.spell#2]
გამარჯობა გაბრიელ მარგიანი,

I was going to finish my beta project of Georgian dictionary on holidays this month, but you have already finished, so I'll discard my project.

The difference of our dictionaries is the number of words.

Your dictionary has more than 84682 words, but mine, extracted from Google Keyboard, has almost 100,000 words.

You can take my beta dictionary and orthography dictionary: https://www.dropbox.com/sh/g2153cqqfjf2w7l/AADCoTJ8DVgSqwtL71E5oDdda?dl=0

When you download them, I'll close my project, so you have already finished. 

I'll contact the developer of Dictionaries.io and ask him to replace my dictionaries for yours.

გილოხავ, გაბრიელ!

Gustavo

**Comment by gamag** [comment]
Hi Gustavo,

Nice to hear from you. I would not say that this project is done - there are way too many wrong words in the dictionary, and I haven't managed to implement an easy way to review them (and I probably won't have the time to work on this until spring.). 

So, before deciding between mine or yours, for something like Dictionaries.io, compare the accuracy please ;-) Google Keyboard might be a much more reliable source than random texts from the Internet (as long as there are no licensing issues).

Counting the number of words is a little hard, since I use affix compression heavily - I think there should be more than 200000 words recognized.

Thank you for your interest and your dictionary, I'll have a look at it when I find the time.

If you actually close your project - any help here would be greatly appreciated :-)

**Comment by gusbemacbe** [comment]
> Google Keyboard might be a much more reliable source than random texts from the Internet (as long as there are no licensing issues).

> Counting the number of words is a little hard, since I use affix compression heavily - I think there should be more than 200000 words recognized.



Google Keyboard uses the same dictionaries from open source Chromium, but Georgian dictionary isn't there. You can use other dictionaries which use circumfix verbs:

https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries/
https://github.com/titoBouzout/Dictionaries

You can run git clone it. 

Observe that Google keyboard became Gboard, my dictionary is aged one year, so outdated, but still has more words than yours, its Georgian dictionary might have already been updated and added more new words. 

Keep your dictionary, search for missed words of my dictionary that are not listed in your dictionary, and copy some of them there to yours.

**Comment by gusbemacbe** [comment]
In my `ka.aff` that was totally developed and made by me, observe that you missed prefix rules of foreign words with Georgian declensions in your affix dictinary, for example:

Mozilla-ის, Mozilla-ში, Mozilla-ზე, Mozilla-თვის, Mozilla-გან, Mozilla-დან, etc.

**Comment by gusbemacbe** [comment]
I tested your dictionary on macOS High Sierra and it worked well:

![screen shot 2017-12-05 at 07 22 12](https://user-images.githubusercontent.com/2257024/33599474-68f099c6-d98d-11e7-90ea-61f79431c052.png)

ბოდიში for not writing in ქართულად, because my Georgian isn't fluent yet because of college.

**Comment by AG12r** [comment]
Hi, 

Not sure where to post this, but can you create and release a dictionary package on AMO website?
Maybe it's not perfect, but it works well enough with Firefox and it's very helpful.

I think it's a good idea to officially add it to Firefox, then it will be accessible to many users.
https://addons.mozilla.org/ka/firefox/language-tools/

Sorry for the inconvenience

**Comment by gusbemacbe** [comment]
I have never heard the AMO website. What is it?

My dictionary and affix dictionary are beta and the affix dictionary is incomplete, as Gabriel missed some rules, maybe he shall merge my affix to his.

**Comment by AG12r** [comment]
AMO is Addons.Mozilla.Org - Firefox Browser extensions

Gabriel has created the ka_GE.spell.xpi package and it can be added to Firefox manually.
But, many user can't do it, so I want to know, if this package, can be submitted to addons website.

**Comment by gusbemacbe** [comment]
It is not true. I am an user, I sent my first dictionary package and it was approved. Check:

https://addons.mozilla.org/ka/firefox/addon/dicion%C3%A1rio-priberam/

As Firefox offered Georgian, I translated my extension informations into Georgian.

**Comment by gamag** [comment]
>  observe that you missed prefix rules of foreign words with Georgian declensions in your affix 
dictinary, for example:
>
>  Mozilla-ის, Mozilla-ში, Mozilla-ზე, Mozilla-თვის, Mozilla-გან, Mozilla-დან, etc.

You are right I don't have those, however since I don't have words in Latin script in my dictionary, there is no use for this affixes - I'll add them when I add foreign words in Latin script. (30-დან etc. probably need some special handling...)

**Comment by gamag** [comment]
> Not sure where to post this, but can you create and release a dictionary package on AMO website?
> Maybe it's not perfect, but it works well enough with Firefox and it's very helpful.

Generally my plan was to do this after adding some easy way to review the word list, but since I didn't manage to implement this for half a year now, and won't have much time to do it during the next months, I should probably change that plan.

So yes, I can create a package and add it to AMO,. I'll do it as soon as I find the time for it.

**Comment by gamag** [comment]
I'm closing this in favor of #3 and #4.
